"""initial schema

Revision ID: 0bbe5e854590
Revises: 
Create Date: 2025-12-23 21:48:57.288757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bbe5e854590'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pollCategories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pollCategories_key'), 'pollCategories', ['key'], unique=True)
    op.create_table('pollTemplates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('pollType', sa.String(length=16), nullable=False),
    sa.Column('maxRank', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['pollCategories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoryId', 'key', name='uq_pollTemplates_category_key')
    )
    op.create_index(op.f('ix_pollTemplates_categoryId'), 'pollTemplates', ['categoryId'], unique=False)
    op.create_index('ix_pollTemplates_category_active', 'pollTemplates', ['categoryId', 'isActive'], unique=False)
    op.create_table('pollInstances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('templateId', sa.String(length=36), nullable=False),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('pollDate', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('pollType', sa.String(length=16), nullable=False),
    sa.Column('maxRank', sa.Integer(), nullable=True),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['pollCategories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['templateId'], ['pollTemplates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('templateId', 'pollDate', name='uq_pollInstances_template_date')
    )
    op.create_index(op.f('ix_pollInstances_categoryId'), 'pollInstances', ['categoryId'], unique=False)
    op.create_index('ix_pollInstances_category_date', 'pollInstances', ['categoryId', 'pollDate'], unique=False)
    op.create_index('ix_pollInstances_date', 'pollInstances', ['pollDate'], unique=False)
    op.create_index(op.f('ix_pollInstances_templateId'), 'pollInstances', ['templateId'], unique=False)
    op.create_table('pollPlans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('templateId', sa.String(length=36), nullable=False),
    sa.Column('pollDate', sa.Date(), nullable=False),
    sa.Column('isEnabled', sa.Boolean(), nullable=False),
    sa.Column('questionOverride', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['templateId'], ['pollTemplates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('templateId', 'pollDate', name='uq_pollPlans_template_date')
    )
    op.create_index('ix_pollPlans_date', 'pollPlans', ['pollDate'], unique=False)
    op.create_index(op.f('ix_pollPlans_templateId'), 'pollPlans', ['templateId'], unique=False)
    op.create_table('pollTemplateOptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('templateId', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['templateId'], ['pollTemplates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('templateId', 'sortOrder', name='uq_templateOptions_template_sort')
    )
    op.create_index('ix_templateOptions_template', 'pollTemplateOptions', ['templateId'], unique=False)
    op.create_table('pollInstanceOptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instanceId', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instanceId'], ['pollInstances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instanceId', 'sortOrder', name='uq_instanceOptions_instance_sort')
    )
    op.create_index('ix_instanceOptions_instance', 'pollInstanceOptions', ['instanceId'], unique=False)
    op.create_table('pollPlanOptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planId', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('sortOrder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['pollPlans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planId', 'sortOrder', name='uq_planOptions_plan_sort')
    )
    op.create_index('ix_planOptions_plan', 'pollPlanOptions', ['planId'], unique=False)
    op.create_table('pollResultSnapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instanceId', sa.String(length=36), nullable=False),
    sa.Column('resultsJson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totalVotes', sa.Integer(), nullable=True),
    sa.Column('totalBallots', sa.Integer(), nullable=True),
    sa.Column('winnerOptionId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instanceId'], ['pollInstances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instanceId', name='uq_pollResultSnapshots_instance')
    )
    op.create_index('ix_pollResultSnapshots_createdAt', 'pollResultSnapshots', ['createdAt'], unique=False)
    op.create_index('ix_pollResultSnapshots_instance', 'pollResultSnapshots', ['instanceId'], unique=False)
    op.create_index(op.f('ix_pollResultSnapshots_instanceId'), 'pollResultSnapshots', ['instanceId'], unique=False)
    op.create_table('voteBallots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instanceId', sa.String(length=36), nullable=False),
    sa.Column('voterTokenHash', sa.String(length=64), nullable=False),
    sa.Column('ipHash', sa.String(length=64), nullable=False),
    sa.Column('userAgentHash', sa.String(length=64), nullable=True),
    sa.Column('countryCode', sa.String(length=2), nullable=True),
    sa.Column('regionCode', sa.String(length=32), nullable=True),
    sa.Column('cityName', sa.String(length=128), nullable=True),
    sa.Column('firstChoiceOptionId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['firstChoiceOptionId'], ['pollInstanceOptions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instanceId'], ['pollInstances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instanceId', 'voterTokenHash', name='uq_voteBallots_instance_voter')
    )
    op.create_index('ix_voteBallots_createdAt', 'voteBallots', ['createdAt'], unique=False)
    op.create_index(op.f('ix_voteBallots_firstChoiceOptionId'), 'voteBallots', ['firstChoiceOptionId'], unique=False)
    op.create_index('ix_voteBallots_instance', 'voteBallots', ['instanceId'], unique=False)
    op.create_index(op.f('ix_voteBallots_instanceId'), 'voteBallots', ['instanceId'], unique=False)
    op.create_index(op.f('ix_voteBallots_voterTokenHash'), 'voteBallots', ['voterTokenHash'], unique=False)
    op.create_table('voteRankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ballotId', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('optionId', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ballotId'], ['voteBallots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optionId'], ['pollInstanceOptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballotId', 'optionId', name='uq_voteRankings_ballot_option'),
    sa.UniqueConstraint('ballotId', 'rank', name='uq_voteRankings_ballot_rank')
    )
    op.create_index('ix_voteRankings_ballot', 'voteRankings', ['ballotId'], unique=False)
    op.create_index(op.f('ix_voteRankings_ballotId'), 'voteRankings', ['ballotId'], unique=False)
    op.create_index('ix_voteRankings_option', 'voteRankings', ['optionId'], unique=False)
    op.create_index(op.f('ix_voteRankings_optionId'), 'voteRankings', ['optionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voteRankings_optionId'), table_name='voteRankings')
    op.drop_index('ix_voteRankings_option', table_name='voteRankings')
    op.drop_index(op.f('ix_voteRankings_ballotId'), table_name='voteRankings')
    op.drop_index('ix_voteRankings_ballot', table_name='voteRankings')
    op.drop_table('voteRankings')
    op.drop_index(op.f('ix_voteBallots_voterTokenHash'), table_name='voteBallots')
    op.drop_index(op.f('ix_voteBallots_instanceId'), table_name='voteBallots')
    op.drop_index('ix_voteBallots_instance', table_name='voteBallots')
    op.drop_index(op.f('ix_voteBallots_firstChoiceOptionId'), table_name='voteBallots')
    op.drop_index('ix_voteBallots_createdAt', table_name='voteBallots')
    op.drop_table('voteBallots')
    op.drop_index(op.f('ix_pollResultSnapshots_instanceId'), table_name='pollResultSnapshots')
    op.drop_index('ix_pollResultSnapshots_instance', table_name='pollResultSnapshots')
    op.drop_index('ix_pollResultSnapshots_createdAt', table_name='pollResultSnapshots')
    op.drop_table('pollResultSnapshots')
    op.drop_index('ix_planOptions_plan', table_name='pollPlanOptions')
    op.drop_table('pollPlanOptions')
    op.drop_index('ix_instanceOptions_instance', table_name='pollInstanceOptions')
    op.drop_table('pollInstanceOptions')
    op.drop_index('ix_templateOptions_template', table_name='pollTemplateOptions')
    op.drop_table('pollTemplateOptions')
    op.drop_index(op.f('ix_pollPlans_templateId'), table_name='pollPlans')
    op.drop_index('ix_pollPlans_date', table_name='pollPlans')
    op.drop_table('pollPlans')
    op.drop_index(op.f('ix_pollInstances_templateId'), table_name='pollInstances')
    op.drop_index('ix_pollInstances_date', table_name='pollInstances')
    op.drop_index('ix_pollInstances_category_date', table_name='pollInstances')
    op.drop_index(op.f('ix_pollInstances_categoryId'), table_name='pollInstances')
    op.drop_table('pollInstances')
    op.drop_index('ix_pollTemplates_category_active', table_name='pollTemplates')
    op.drop_index(op.f('ix_pollTemplates_categoryId'), table_name='pollTemplates')
    op.drop_table('pollTemplates')
    op.drop_index(op.f('ix_pollCategories_key'), table_name='pollCategories')
    op.drop_table('pollCategories')
    # ### end Alembic commands ###
